// <auto-generated />
using System;
using DataPlus.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataPlus.Entities.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190626042721_AddCoursesModels")]
    partial class AddCoursesModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataPlus.Entities.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("DataPlus.Entities.Models.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CourseId");

                    b.Property<int>("EnrollmentStatus");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("DataPlus.Entities.Models.EnrollmentSignature", b =>
                {
                    b.Property<Guid>("EnrollmentId");

                    b.Property<Guid>("SignatureId");

                    b.HasKey("EnrollmentId", "SignatureId");

                    b.HasIndex("SignatureId");

                    b.ToTable("EnrollmentSignature");
                });

            modelBuilder.Entity("DataPlus.Entities.Models.EnrollmentStudent", b =>
                {
                    b.Property<Guid>("EnrollmentId");

                    b.Property<Guid>("StudentId");

                    b.HasKey("EnrollmentId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("EnrollmentStudent");
                });

            modelBuilder.Entity("DataPlus.Entities.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Level");

                    b.Property<string>("Logger");

                    b.Property<string>("Message");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DataPlus.Entities.Models.Signature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Signature");
                });

            modelBuilder.Entity("DataPlus.Entities.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Birth");

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("DocumentType");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("DataPlus.Entities.Models.Teacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Birth");

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<int>("DocumentType");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("DataPlus.Entities.Models.Enrollment", b =>
                {
                    b.HasOne("DataPlus.Entities.Models.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataPlus.Entities.Models.EnrollmentSignature", b =>
                {
                    b.HasOne("DataPlus.Entities.Models.Enrollment", "Enrollment")
                        .WithMany("EnrollmentSignatures")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataPlus.Entities.Models.Signature", "Signature")
                        .WithMany("EnrollmentSignatures")
                        .HasForeignKey("SignatureId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataPlus.Entities.Models.EnrollmentStudent", b =>
                {
                    b.HasOne("DataPlus.Entities.Models.Enrollment", "Enrollment")
                        .WithMany("EnrollmentStudents")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataPlus.Entities.Models.Student", "Student")
                        .WithMany("EnrollmentStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
